### PR TITLE
ESCP-4040: Address ds3_java_cli 3rd party dependencies open CVEs

### PR DESCRIPTION
**Pull request by lesserwhirls**
Also, take the opportunity to update gradle to 8.3 and the various gradle plugins to their latest release.

### CODE REVIEW

**Review by scribe — DISMISSED** [review]

**Comment by lesserwhirls** [comment]
Since this is a fairly major update, dependency-wise (`ds3_java_sdk` `5.1.3` to `5.6.0`), we should discuss what to do with the project version (currently `5.1.4`) before this goes in.

**Comment by lesserwhirls** [comment]
pinging @RachelTucker

**Review by scribe — DISMISSED** [review]

**Comment by lesserwhirls** [comment]
Updated to the ds3_java_sdk v5.6.2 release and fixed the expected output for a test.

**Comment by lesserwhirls** [comment]
So now back to the versioning question...since this is a fairly major update, dependency-wise (ds3_java_sdk 5.1.3 to 5.6.2), we should discuss what to do with the project version (currently 5.1.4) before this goes in.

**Comment by RachelTucker** [comment]
The convention for the SDKs and CLI is to match the BP major minor version and use the patch for the client. In this case that would mean this should be CLI 5.6.0.

**Comment by lesserwhirls** [comment]
Sounds good! Should I create a 5.6.0 release as part of this PR, or set it as 5.6.0-SNAPSHOT until we're ready for a release?

**Comment by lesserwhirls** [comment]
> Should I create a 5.6.0 release as part of this PR, or set it as 5.6.0-SNAPSHOT until we're ready for a release?

Went ahead and set the version to 5.6.0, then bumped to 5.6.1-SNAPSHOT.

**Review by scribe — APPROVED** [review]

**Review by david-limbach — APPROVED** [review]

**Pull request merged**
